apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-node
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-back-deployment
  labels:
    app: node-back-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-back-app
  template:
    metadata:
      labels:
        app: node-back-app
    spec:
      containers:
      - name: spring
        image: us.gcr.io/proyecto-kubernetes-297222/node-back
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: vol
            mountPath: /app/resources/static/assets/uploads
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: pvc-node